#166677241 create tag model
andela/king-kong-ah-backend pull request #23
Opened 2019-06-18 17:26 UTC by akinyeleolat

#### What does this PR do?
This PR sets up tag model

#### Description of Task to be completed?
- add tag migration and model
- update article and tag associations
- add test script for  tag model
- update test script for article model

#### How should this be manually tested?
- Clone the repo
- Run ```npm install```
- Run ```npm run test```

#### Any background context you want to provide?
- You need `node` and `npm` installed 
- Run ```npm install``` to install dependencies
- You need sequelize-cli installed globally on your local machine
- Run ```sequelize db:migrate``` on the console from the root of the application. 

#### What are the relevant pivotal tracker stories?
[166761453](https://www.pivotaltracker.com/story/show/166761453)

2019-06-18 18:54 UTC, Sojisoyoye approved these changes
Good job Tosin.

2019-06-18 19:03 UTC, Eazybee requested changes
Good job @akinyeleolat. However, I left some feedback you might want to reflect on.

2019-06-18 19:03 UTC, Eazybee commented on server/migrations/tagArticle.js
> +      primaryKey: true,
You might want to remove `primaryKey:true`

2019-06-18 19:03 UTC, Eazybee commented on server/migrations/tagArticle.js
> +      defaultValue: Sequelize.UUIDV4
I don't think `defaultValue: Sequelize.UUIDV4` should be set

2019-06-18 19:03 UTC, Eazybee commented on server/tests/models/tag.spec.js
> +      expect(tag).to.equal(undefined);
the code won't get here because an error would have been thrown already on line 26.
you should consider removing `expect(tag).to.equal(undefined);` in line 27

2019-06-18 19:03 UTC, Eazybee commented on server/tests/models/tag.spec.js
> +      expect(tag).to.equal(undefined);
same here

2019-06-18 19:03 UTC, Eazybee commented on server/tests/models/tag.spec.js
> +      return expect(name).to.be.equal('excellence');
I don't think the use of `return` here is appropriate

2019-06-18 19:03 UTC, Eazybee commented on server/tests/models/tag.spec.js
> +      return expect(tag).to.equal(undefined);
same here

2019-06-18 19:03 UTC, Eazybee commented on server/tests/models/tag.spec.js
> +      return expect(found).to.equal(null);
same here

2019-06-18 20:10 UTC, Eazybee approved these changes

2019-06-19 08:55 UTC, benfluleck commented on server/app.js
> +const port = process.env.PORT;
Why?

2019-06-19 08:56 UTC, benfluleck commented on server/migrations/tagArticle.js
> +const TagArticles = {
Why is the name in migration different from the model name? 🤷‍♂

2019-06-19 08:59 UTC, benfluleck requested changes
I see no tests for the relationship between tags and articles. How far na

2019-06-19 19:33 UTC, benfluleck approved these changes

2019-06-19 19:33 UTC, merged