#166272104 Password Reset
andela/king-kong-ah-backend pull request #25
Opened 2019-06-19 13:45 UTC by mosinmiloluwa01

#### What does this PR do?
This PR implements password reset feature

#### Description of Task to be completed?
- write tests
- implement recover email feature
- implement reset password feature
- create middleware for validation

#### How should this be manually tested?
- input "http://localhost:3000/api/v1/auth/recoverEmail" post route on postman
- supply the user's email
- click on send
- Go to your email, click on the "recover password" button 
- the button takes you to the browser, copy the link and input in postman
- input a new password and confirm password
- click on send

#### Any background context you want to provide?
User must have node and postman installed

#### What are the relevant pivotal tracker stories?
[166272104](https://www.pivotaltracker.com/story/show/166272104)

2019-06-19 15:15 UTC, Eazybee submitted a review, later dismissed

2019-06-19 15:15 UTC, Eazybee commented on server/tests/controller/recoverEmail.spec.js
> +        expect(res.status).to.be.equal(404);
you might want to test more than just status code

2019-06-19 15:15 UTC, Eazybee commented on server/tests/controller/recoverEmail.spec.js
> +  it('should not send email with an incorrect email', (done) => {
new line needed here for readability

2019-06-19 15:15 UTC, Eazybee commented on server/tests/controller/recoverEmail.spec.js
> +  it('should not send email with a correct email', (done) => {
same here

2019-06-19 15:15 UTC, Eazybee commented on server/tests/controller/resetPassword.spec.js
> +  it('should not reset password if password has an incorrect format', (done) => {
same here

2019-06-19 15:15 UTC, Eazybee commented on server/tests/controller/resetPassword.spec.js
> +  it('should not send email with a correct email', (done) => {
same here

2019-06-21 15:08 UTC, akinyeleolat approved these changes

2019-06-21 15:13 UTC, EmmanuelSage approved these changes

2019-06-21 18:14 UTC, benfluleck commented on server/emailTemplates/recoverEmail.js
> +  const token = tokenGenerator('noid', false, process.env.TOKEN_EXPIRY_DATE, process.env.SECRET, email);
What is noid ?

2019-06-21 18:17 UTC, benfluleck commented on server/emailTemplates/recoverEmail.js
> +  const token = tokenGenerator('noid', false, process.env.TOKEN_EXPIRY_DATE, process.env.SECRET, email);
why is `isVerified` set to false for a rest email ?

2019-06-21 18:22 UTC, benfluleck commented on server/emailTemplates/recoverEmail.js
> +const generateEmail = (email, req) => {
shouldn't this be named `generateResetEmail`

2019-06-21 18:29 UTC, benfluleck commented on server/helpers/utils.js
> +  if (email && toLowerCaseAndTrim(email) !== '') {
What is this line doing? Why not simply `if(email)`

2019-06-21 18:32 UTC, benfluleck requested changes
Changes requested also rebase

2019-06-22 05:49 UTC, benfluleck approved these changes

2019-06-22 05:49 UTC, merged