#166859551 create bookmark model
andela/king-kong-ah-backend pull request #32
Opened 2019-06-22 23:58 UTC by Eazybee

#### What does this PR do?
This PR  creates bookmark model

#### Description of Task to be completed?
 - create bookmark migration file
 - add association to user and article
 - write tests for bookmark model
 - refactor readingStats model

#### How should this be manually tested?
- Run ```npm run test```

#### Any background context you want to provide?
- You need `node` and `npm` installed 
- Run ```npm install``` to install dependencies 
- You need to install an editorconfig extension in your vscode

#### What are the relevant pivotal tracker stories?
[#166859551](https://www.pivotaltracker.com/story/show/166859551)

2019-06-23 03:38 UTC, akinyeleolat requested changes
Well done @Eazybee, you have only tested the relationship and not the model itself.

2019-06-23 19:54 UTC, EmmanuelSage approved these changes
I see you took advantage of the fact that it is a pivot table by using magic methods.
Good job

2019-06-23 22:45 UTC, akinyeleolat approved these changes

2019-06-24 11:41 UTC, benfluleck commented
@mosinmiloluwa01 created a route to add a comment. Be like @mosinmiloluwa01 .

2019-06-24 11:45 UTC, merged